organizationIdentifier clarifications
srdavidson/smime pull request #12
Opened 2024-09-26 09:07 UTC by XolphinMartijn

2024-09-30 13:07 UTC, srdavidson requested changes

2024-09-30 13:07 UTC, srdavidson commented on SBR.md
> +   __Contents:__ If present, the `subject:organizationIdentifier` field SHALL contain a Registration Reference for a Legal Entity assigned in accordance to the identified Registration Scheme. The Reg
andjurisdiction ... fix spacing

The Registration Reference SHOULD be unique where the Registration Scheme and jurisdiction provide unique identifiers.

2024-09-30 13:12 UTC, XolphinMartijn commented on SBR.md
> +   __Contents:__ If present, the `subject:organizationIdentifier` field SHALL contain a Registration Reference for a Legal Entity assigned in accordance to the identified Registration Scheme. The Reg
```suggestion
   __Contents:__ If present, the `subject:organizationIdentifier` field SHALL contain a Registration Reference for a Legal Entity assigned in accordance to the identified Registration Scheme. The Registration Reference SHOULD be unique where the scheme and jurisdiction provide unique identifiers. 
```

2024-10-02 16:32 UTC, srdavidson approved these changes

2024-10-02 16:32 UTC, merged